### ISSUE TITLE
Demo App Menu Structure

### ISSUE THREAD

**Issue by radu2501** [consultingwerk/SmartComponentsAngularDemo#6]
I am now in a skype call with Martyn, and we noticed some problems with the Demo App menu structure:

- Dynamic Customer Maint throws a "Cannot start business entity" error. Should that menu item even be present, given that it is probably aiming to display the same view as the Custoemer Maintenance item?
- Customers by Salesrep (Tabstrip) - this also errors on load. I believe it should not be there at all, as the only "tabstrip" that we currently have is the MDI interface.
- Salesreps (with Chart) - errored; isn't that displayed in the "Start" page?
- There are two "Order Maintenance" menu items - I believe only the first one should be there
- Orderline Maintenance - the datasource in this view does not include the `partial-dataset="true"` setting, which causes the grid to not display any records
- Customer (static viewer) - only the grid is displayed, the viewer is reporting that it cannot find the CustomerViewer.html template file

**Comment by mikefechner** [comment]
Won't fix that! Those items are on the menu now since over a year.

This is not a public un-attended demo. Folks running the demo will know.

**Comment by radu2501** [comment]
I will let Martyn know, since he was unsure which forms he should be running and which are not functional.
